---
- name: "Gathering OpenShift infrastructure information"
  hosts: localhost
  connection: local

  vars_prompt:
    - name: "num_of_masters"
      prompt: "How many master nodes do you want to configure? "
      default: "1"

    - name: "num_of_nodes"
      prompt: "How many nodes do you want to configure? "
      default: "2"
